### ISSUE TITLE
Cryptic error when building sites

### ISSUE THREAD

**Issue by embano1** [tomanistor/osprey#11]
Hi,

Followed the basic tutorial from your themes page. `hugo server -D` and `hugo` throws this error message which I cannot resolve:
```
Started building sites ...
ERROR 2017/07/30 22:35:27 Error while rendering "home": template: theme/index.html:3:3: executing "theme/index.html" at <partial "gallery.htm...>: error calling partial: template: theme/partials/gallery.html:27:17: executing "theme/partials/gallery.html" at <after 3 (where .Site...>: error calling after: no items left
```
go version: go version go1.8.3 darwin/amd64 
hugo version: Hugo Static Site Generator v0.25.1 darwin/amd64 BuildDate: 2017-07-30T19:27:07+02:00

**Comment by tomanistor** [comment]
Thanks for alerting me. This is an error with the last gallery feature update. Fixing it now. In the meantime, [v1.1.0](https://github.com/tomanistor/osprey/releases/tag/v1.1.0) will still build if you'd like to revert to the earlier release.

The problem arises when there are less than three "gallery" section items in the content folder.

**Comment by tomanistor** [comment]
Hi @embano1, I pushed up some new changes that should fix this bug with the gallery build. Please let me know if it solves the issue for you as well.
