### ISSUE TITLE
/images/logo/manifest.json?

### ISSUE THREAD

**Issue by TheHackerDev** [tomanistor/osprey#16]
The theme tries to load `/images/logo/manifest.json` [here](https://github.com/tomanistor/osprey/blob/master/layouts/partials/header.html#L66), but it does not include this file anywhere. What is this for?

Cheers,
Aaron ([insp3ctre](https://twitter.com/insp3ctre))

**Comment by tomanistor** [comment]
Hey @insp3ctre, that is the `manifest.json` file used for Android Chrome to add a favicon icon to the homescreen.

https://developer.chrome.com/multidevice/android/installtohomescreen#supporting

It is not included in the site build but it should be created by the developer when uploading favicons for their site.

However, I didn't include instructions for that and it really shouldn't be automatically added in like it currently is. That whole favicon section should be rewritten, so thank you for bringing it up!

**Comment by TheHackerDev** [comment]
No problem, thanks for the quick turnaround!
