### ISSUE TITLE
logoSmall is too small

### ISSUE THREAD

**Issue by TheHackerDev** [tomanistor/osprey#17]
When I scroll down the page, the image in the top left corner gets trimmed down to 50x13! That's so tiny, you can't see any part of it. Is there some way to make that bigger?

Relevant line: https://github.com/tomanistor/osprey/blob/master/layouts/partials/header.html#L103

Cheers,
Aaron ([insp3ctre](https://twitter.com/insp3ctre))

**Comment by tomanistor** [comment]
This is because that space has a max-width of 50px to avoid distorting the top nav with larger images. I can increase the max-width a bit and add a max-height instead that should work.
