### ISSUE TITLE
How did you compile the CSS?

### ISSUE THREAD

**Issue by TheHackerDev** [tomanistor/osprey#20]
I'm trying to update the SCSS file and recompile it using the `scss` tool, but I can't seem to output the same type of CSS file as is included in the theme. How did you compile your SCSS file into CSS?

Cheers,
Aaron ([insp3ctre](https://twitter.com/insp3ctre))

**Comment by tomanistor** [comment]
I use Gulp to compile SCSS files into minified CSS files. Here is the gulpfile I use for example:
https://github.com/tomanistor/tomanistor.com/blob/master/gulpfile.babel.js

I made the theme so you shouldn't have to edit the SCSS files though. It should be a little easier to inject custom CSS in snippets via these instructions:
https://github.com/tomanistor/osprey#custom-css

Unless you have a lot of CSS changes to make, then it would be better to install Gulp and make it part of your workflow. This is a great guide for doing that:
http://danbahrami.io/articles/building-a-production-website-with-hugo-and-gulp-js/
