### ISSUE TITLE
More loyal open source license?

### ISSUE THREAD

**Issue by avkonst** [tomanistor/osprey#23]
Nice work. Users of your theme should publish their websites under GPL3 license too. It is not appropriate for my case, but I like your theme. Would you be able to change it to MIT or Apache 2?

**Comment by tomanistor** [comment]
Thanks @avkonst. I haven't given the license much thought besides ensuring that the theme is maintained as open source and free to use. I believe the GPL3 license ensures that this theme can remain that way if it were forked and improved by other parties. I'm not sure that websites that use this teme need to have this license though, but that may be wrong.

Are there reasons it should be MIT or Apache 2 instead?

**Comment by avkonst** [comment]
Any derivative work or any work which links to / with the GPL3 should be released under GPL3. So, websites based on this template are linking to / built from (by hugo compilation) this GPL3 template should be also published under GPL3. I picked Apache 2 or MIT as most frequently used licenses which do not have the same restrictions as GPL3.

**Comment by tomanistor** [comment]
Will the switch from GPL3 to Apache 2 or MIT require permission from each current contributor?

**Comment by avkonst** [comment]
I would say no:
- if you are a single owner of the related IP (yes, you are still the owner even if it is currently open source)
- and if you do not have specific agreement signed with the contributors

You may want to seek for the second opinion.

**Comment by tomanistor** [comment]
I'd like to change the license of this project from GPLv3 to a more permissive license like Apache 2 or MIT and continue development under one of those licences. Before I do so, I'd like to get the OK from all current contributors.

As @avkonst mentioned previously, the current GPLv3 license requires that all modifications to code, or works derived from this code, must be licensed under the same open source terms. This might be preventing individuals and companies from contributing or using the theme.

At this point, I'm leaning more toward Apache 2 as it is permissive and includes patent protections, but I'm very open to everyone's input - whether in the form of a comment, or just a 👍or 👎.

* https://choosealicense.com/
* https://exygy.com/which-license-should-i-use-mit-vs-apache-vs-gpl/
* https://snyk.io/blog/mit-apache-bsd-fairest-of-them-all/

CC @gerl1ng @jakkan @ntrossat @mischapeters @gam-phon @globetrotter @bangfalse 

Thanks for your time and your code additions!

**Comment by mischapeters** [comment]
Everything better than GPL. :)
So 👍 from me for the very limited contribution I have done.

**Comment by bangfalse** [comment]
👍

**Comment by tomanistor** [comment]
Thanks for the responses, everyone. I have yet to hear from @gam-phon and @globetrotter and I emailed gam-phon but have not been able to reach globetrotter.

One of the upcoming releases will be under the Apache 2 license.

**Comment by gam-phon** [comment]
I'd like to change the license of this project from GPLv3 to a more permissive license like Apache 2 or MIT and continue development under one of those licences.

**Comment by gam-phon** [comment]
Of course it is 👍

**Comment by justyn** [comment]
So just to confirm, is it okay to use this theme under Apache 2 license terms?

**Comment by tomanistor** [comment]
@justyn Yes it is, and I will change the license in the repo shortly.

**Comment by tomanistor** [comment]
Here is the commit changing the license from GPL 3 to Apache 2: https://github.com/tomanistor/osprey/commit/7bcf31c2ba5dcb947ff2575c905e476ae631ccaf
