### ISSUE TITLE
Size of the frontal page image

### ISSUE THREAD

**Issue by StevenPuttemans** [tomanistor/osprey#24]
is it possible to somehow quickly change the allowed dimensions of the image that is rendered on the front page? I would like to add a larger one but cannot find where the dimensions of this object are defined...

**Comment by klubiniecki** [comment]
Hey @StevenPuttemans ! 

Is this what you're looking for?

<img width="714" alt="screen shot 2017-10-20 at 13 12 13" src="https://user-images.githubusercontent.com/22548703/31818423-56fa4faa-b598-11e7-96d1-cfa6ef670263.png">

**Comment by StevenPuttemans** [comment]
Yep that is what I want

**Comment by klubiniecki** [comment]
Allright!

Here: https://github.com/tomanistor/osprey/blob/master/layouts/partials/header.html

` {{ if .IsHome }}
        <header class="row middle-xs center-xs">
            <div class="col-xs-12">
                <div class="row middle-xs center-xs">
                    <div class="col-xs-12"><img src="{{ .Site.Params.logoBig}}" alt="{{ .Site.Title }}"></div>
                </div>`

Change the `img` max-height property to something else like `15 rem`. 

So in your SASS add for example:
header {
 img {
  max-height: 15rem;
  }
}

Hope that helps!
