### ISSUE TITLE
Question about gallery

### ISSUE THREAD

**Issue by StevenPuttemans** [tomanistor/osprey#26]
So I ran the sample gallery `hugo new gallery/image-title.md`

Inside the file I added

```
---
title: "Image Title"
date: 2017-10-07T14:38:42+02:00
draft: false
---

+++
date = "2017-05-10T21:35:17-07:00"
title = "Image Title"
image = "osprey-logo.png"
alt = "This is a description of the image"
color = "#7ac143"
link1 = "https://tomanistor.com"
link2 = "https://github.com/tomanistor"
+++
```

But it keeps loading as 

![afbeelding](https://user-images.githubusercontent.com/4621239/31307953-f85b758e-ab6d-11e7-94eb-e562980b592c.png)

Notice the broken link symbol. So I am wondering how to get the gallery running, which is the final part I need right now.

**Comment by StevenPuttemans** [comment]
Found it, simply need to replace the whole header ...

**Comment by tomanistor** [comment]
It looks like you had both a YAML and TOML front matter in your file. Just need one of the two.
