### ISSUE TITLE
Custom font

### ISSUE THREAD

**Issue by hfogelberg** [tomanistor/osprey#33]
Nice work!

One question though: is it possible to use a custom (Google) font? In that case how?
Except for fiddling with the generated html of course.

**Comment by tomanistor** [comment]
Thank @hfogelberg! It should work with the custom CSS file. The instructions are in the theme's [README.md](https://github.com/tomanistor/osprey/blob/master/README.md) for doing so.

Import a Google font at the top of the file, and then override the current font families with the new Google font.
