### ISSUE TITLE
Contact form, isn't working (even in demo)

### ISSUE THREAD

**Issue by gustavotero7** [tomanistor/osprey#34]
Hi, I have  a little problem, 

I have done the verification with formspree.io, and I have tested it and works (outside the Hugo site)

But when I try it in my site it doesn't work, nothing happen. the site I'm testing is [www.chimera.digital](http://www.chimera.digital)

How can I make it work?

PD: email field is set in the config.toml file, I have verified the HTML result and the output it's right
`<form id="form-contact" action="https://formspree.io/contact@chimera.digital" method="POST">`

PD2: In the demo site the form neither works. But in the tomanistor site it works well, I can see email sent message (sorry for the blank email)

**Comment by tomanistor** [comment]
Thanks for bringing this up @gustavotero7.

Recently, I've discovered that FormSpree has disabled AJAX for all newly created forms that are not made on a FormSpree Gold account: https://github.com/formspree/formspree/pull/173

Without diving into the problem yet, I can only assume it is related to that. I am considering replacing FormSpree with another contact form service that freely allows AJAX calls so that new forms can work as intended.

**Comment by gustavotero7** [comment]
Got it, removed AJAX script and works well, I think later I will get gold, but now works well.

Thanks

**Comment by jasonna2607** [comment]
Hi @gustavotero7 I was wondering can I have a look on your code? 

Got the same error as you have and went on tried the default coding FormSpree provides and it seems that it will bring me to the reCAPTCHA page which I'm trying to avoid now

**Comment by gustavotero7** [comment]
Hi @jasonna2607 I had remoed the ajax js script, also in my case the contact form redirects to the formspree captcha page. 

Now I have restored the ajax script, and is working, I don't have a formspree paid account, not sure why is working now.

**Comment by ragasirtahk** [comment]
Can you people guide me on this issue? Please tell me how to get the form working? How do I remove the AJAX script being talked about? My code: https://github.com/ragasirtahk/Me

**Comment by jasonna2607** [comment]
hmm i think they mentioned about old forms being usable without paying. I'm
a new user that explains why AJAX does not work on me. Thanks for the reply
tho!

**Comment by gustavotero7** [comment]
Hi @ragasirtahk, if you have validated your site with formspree just change `ajaxFormspree` to `false` in your config.toml file.

or

remove  line 6 osprey/layouts/partials/body-bottom.html

**Comment by ragasirtahk** [comment]
Thank you @gustavotero7
Edit: I changed the value to false, but this removed the contact form from my website. Please check out my repo and help me.

**Comment by gustavotero7** [comment]
@ragasirtahk create a copy of  `osprey/layouts/partials/body-bottom.html ` file inside `your-site/layouts/partials `and comment the line 6 of that file. that will override the original `osprey body-bottom.html `and remove the ajax script.

**Comment by ragasirtahk** [comment]
Thank you @gustavotero7 
Everything works fine now.

**Comment by sbesnard** [comment]
Hi all, @gustavotero7 your solution should appear in the README.MD

**Comment by tomanistor** [comment]
Thanks for assisting, @gustavotero7! If you or anyone wants to create a PR to add that to the `README.md`, please do and I'll merge it. In the meantime, I am looking for alternative contact form services that allow AJAX.
