### ISSUE TITLE
adding a carousel 

### ISSUE THREAD

**Issue by ghost** [tomanistor/osprey#39]
I was wondering if there was a way to add a  carousel to the theme? I tried to add an image carousel using instructions form the Hugo universal theme. (with owl.js) I couldn't figure out how to do it. I was wondering how I would go about adding a small image carousel under the main logo. Or maybe creating a separate partial for it. I'm new to Hugo

**Comment by tomanistor** [comment]
@yeah-nothing, this would require copying the `osprey/layouts/partials/body-top.html` file in the theme folder and adding it to your hugo folder under `yourHugoSite/layouts/partials`.

Your new, duplicated file will overwrite the theme file and you'll be able to edit this area and insert your carousel:

```{{ if .IsHome }}
  <header class="row middle-xs center-xs">
    <div class="col-xs-12">
      <div class="row middle-xs center-xs">
        <div class="col-xs-12"><img src="{{ .Site.Params.logoBig}}" alt="{{ .Site.Title }}"></div>
      </div>
      <div class="row middle-xs center-xs">
        <div class="col-xs-12">
          <h1>{{ .Site.Params.tagline }}<span class="cursor">|</span></h1>
        </div>
      </div>
    </div>
  </header>
{{ end }}
```

You'll likely have to add some JavaScript. I would recommend doing the same thing with the `osprey/layouts/partials/body-bottom.html` and adding it in there as a script link or inline.
