### ISSUE TITLE
hugo server onlocal host not see blog

### ISSUE THREAD

**Issue by zphj1987** [tomanistor/osprey#44]
thank you for your job ,your themes is very beautiful 

i push it to github pages it work good 

but when i start it with  hugo server   on mylocal host  i found the blog not see 

on local host see:

![111111111](https://user-images.githubusercontent.com/2322061/39350787-d07f4866-4a31-11e8-9cde-c6ef93d9e2c7.png)

![222222](https://user-images.githubusercontent.com/2322061/39350793-d59eed9c-4a31-11e8-8d0d-f068c9fda5c3.png)

on github pages see:
![3333333](https://user-images.githubusercontent.com/2322061/39350807-daeb33f0-4a31-11e8-88a2-a80e6cd5ffb0.png)

**Comment by tomanistor** [comment]
Hi @zphj1987,

It might be caused by the way the `config.toml` file is configured. Make sure the baseURL is set correctly to your site address.
