### ISSUE TITLE
Don't steal jQuery $

### ISSUE THREAD

**Issue by adammhaile** [tomanistor/osprey#45]
I'm loving Osprey but I was trying to add some gallery support to my site which uses jQuery and had a heck of time trying to figure out why it didn't work only to finally realize that Osprey completely steals the $ jQuery shortcut: https://github.com/tomanistor/osprey/blob/master/static/scripts/src/main.js#L1-L2
To get things to work I had to rename $ and $$ in the Osprey files so they didn't conflict with standard jQuery.
I totally appreciate leaving out jQuery from your theme and but wanting the convenience of the $ and $$ shortcuts, but it would be great if it didn't preclude you from using Osprey *and* something else that uses jQuery.

Thanks!

**Comment by tomanistor** [comment]
Hey sorry about that @adammhaile. Didn't mean to make you go on an unnecessary bug hunt. I realize now that I should have nested those $ and $$ variable declarations in an anonymous function in case people use jQuery. This will be fixed.
