### ISSUE TITLE
Navbar drawing over homepage

### ISSUE THREAD

**Issue by acammies** [tomanistor/osprey#50]
Clicking the homepage image when the navbar is open on mobile devices leads to both being drawn onscreen at the same time. Will try to fix later.
Steps to recreate: F12 + select mobile view, click hamburger icon, click homepage icon

**Comment by chinkung** [comment]
I have created PR #55 to fix this issue.

**Comment by tomanistor** [comment]
Thank you for finding this bug @acammies and thank you @chinkung for fixing it!
