### ISSUE TITLE
Template fails a wercker based Hugo build

### ISSUE THREAD

**Issue by RichardSage** [tomanistor/osprey#6]
i've been trying to use osprey as the theme for a hugo site hosted on github pages, using wercker to automatically build the site based on a push. The following is a list of errors that cause the wercker hugo build to fail
ERROR: 2017/07/04 template: theme/_default/list.html:6: function "humanize" not defined
ERROR: 2017/07/04 template: theme/_default/single.html:8: function "default" not defined
ERROR: 2017/07/04 template: theme/partials/about.html:3: function "readDir" not defined
ERROR: 2017/07/04 template: theme/partials/blog.html:12: function "default" not defined
ERROR: 2017/07/04 Error while rendering section : html/template: "theme/_default/list.html" is an incomplete template

**Comment by tomanistor** [comment]
Hey @RichardSage, what versions of Hugo and GoLang are you using?

**Comment by RichardSage** [comment]
Hi Toma,

Hugo version is 0.14. The Werker package doesn't specify the version of
GoLang

**Comment by tomanistor** [comment]
You'll need the latest version of Hugo because 0.14 doesn't use those functions. This theme in particular works best with the current version of Hugo: 0.24.1.

https://github.com/gohugoio/hugo/releases

**Comment by RichardSage** [comment]
Thanks Toma, I'll look at changing it.

As an aside I noticed during building my site that I had to put assets (e.g
images) into the images folder within the theme folder for them to display,
not within the image folder within the main part of my project. I'm
assuming in probably doing something stupid, is there a config setting that
I might need to change?

Thanks in advance

**Comment by tomanistor** [comment]
What is your static folder structure? The path to an image in the theme is `/images/example-image.jpg`.

In the config.toml file, for example, you can use your own logo by changing
```
logoBig = "/images/osprey-logo.png"
```
to your own image path.

**Comment by RichardSage** [comment]
Hello Toma,

I've re-installed the theme, but i'm still having issues with images in my
/images/ folder not displaying (they do if i put them in the /images folder
within the theme folder).

I've attached 3 screenshots of the 404, one of the example galleries where
the image is not displaying, and the folder structure.

I'd really appreciate it if you could point me in the right direction as to
how to resolve this as i'd relly like to use your theme for my site.

Thanks in advance

Richard

**Comment by RichardSage** [comment]
Hello Toma,

I think i've resolved the issue, i created an images folder in the static
folder in the root of my site (so root/static/images) and put my image in
there and they are now displaying.

**Comment by tomanistor** [comment]
Ah yes, I assumed your images folder was inside of the static folder already. Here is the Hugo doc on directory organization: https://gohugo.io/overview/source-directory/

Glad it's working now!
