### ISSUE TITLE
Docs on how to use sass variables to change font etc

### ISSUE THREAD

**Issue by nehiljain** [tomanistor/osprey#72]
I am new to Hugo and love the theme. I couldn't figure out how to change font with sass variables. It should be fairly easy but I don't see any docs or configs on it.

**Comment by tomanistor** [comment]
Hey @nehiljain, SASS variables for this theme can't be changed as it is currently written. The theme might need to be forked if you wanted to change the source code or you could overwrite any of the theme's styling by using the theme's custom CSS capabilities as instructed here: https://github.com/tomanistor/osprey#custom-css

**Comment by nehiljain** [comment]
Thanks, custom css did the job for me.
